/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import client_server.ClientServer;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import sinhvien.Diem;
import sinhvien.ThongTin;

/**
 *
 * @author Administrator
 */
public class Client extends javax.swing.JFrame {

    private static final String url="//192.168.1.2/server";
    
    private static  String masv,mamh,hocky,lan;
    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
//        eo.setVisible(false);
        lbloi.setText("");
        anThongTin();
        anCapNhat();
        anTable();
        if(combo.getSelectedIndex()==0)
            hienThongTin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yah = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        txtTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        lbloi = new javax.swing.JLabel();
        lbthongtin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbstt = new javax.swing.JLabel();
        lbmsv = new javax.swing.JLabel();
        lbho = new javax.swing.JLabel();
        lbten = new javax.swing.JLabel();
        lbmalop = new javax.swing.JLabel();
        lbgioitinh = new javax.swing.JLabel();
        lbngaysinh = new javax.swing.JLabel();
        lbnoisinh = new javax.swing.JLabel();
        lbdiachi = new javax.swing.JLabel();
        lbghichu = new javax.swing.JLabel();
        lbnghihoc = new javax.swing.JLabel();
        txtmsv = new javax.swing.JTextField();
        txtho = new javax.swing.JTextField();
        txtten = new javax.swing.JTextField();
        txtnoisinh = new javax.swing.JTextField();
        txtghichu = new javax.swing.JTextField();
        txtmalop = new javax.swing.JTextField();
        txtgioitinh = new javax.swing.JTextField();
        txtngaysinh = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        txtnghihoc = new javax.swing.JTextField();
        eo = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        edtenmon = new javax.swing.JLabel();
        edhocky = new javax.swing.JLabel();
        edlan = new javax.swing.JLabel();
        lbdiem = new javax.swing.JLabel();
        eddiem = new javax.swing.JTextField();
        btncapnhat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 150));

        yah.setBackground(new java.awt.Color(204, 204, 255));
        yah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("QUẢN LÝ ĐIỂM SINH VIÊN");
        yah.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xem thông tin", "Xem điểm", "Cập nhật điểm" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        yah.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 120, -1));

        txtTim.setForeground(new java.awt.Color(102, 102, 102));
        txtTim.setText("Nhập mã sinh viên...");
        txtTim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickTim(evt);
            }
        });
        txtTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimActionPerformed(evt);
            }
        });
        yah.add(txtTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 152, -1));

        btnTim.setText("Xem");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        yah.add(btnTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        lbloi.setForeground(new java.awt.Color(255, 0, 51));
        lbloi.setText("Không tìm thấy!");
        yah.add(lbloi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, 34));

        lbthongtin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbthongtin.setText("THÔNG TIN SINH VIÊN");
        yah.add(lbthongtin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, 27));

        jLabel2.setText("Status:");
        yah.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        lbstt.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbstt.setText("status...");
        yah.add(lbstt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));

        lbmsv.setText("Mã sinh viên:");
        yah.add(lbmsv, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 80, 20));

        lbho.setText("Họ:");
        yah.add(lbho, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        lbten.setText("Tên:");
        yah.add(lbten, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        lbmalop.setText("Mã lớp:");
        yah.add(lbmalop, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, 20));

        lbgioitinh.setText("Giới tính:");
        yah.add(lbgioitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        lbngaysinh.setText("Ngày sinh:");
        yah.add(lbngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        lbnoisinh.setText("Nơi sinh:");
        yah.add(lbnoisinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        lbdiachi.setText("Địa chỉ:");
        yah.add(lbdiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        lbghichu.setText("Ghi chú:");
        yah.add(lbghichu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        lbnghihoc.setText("Nghỉ học:");
        yah.add(lbnghihoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, -1, -1));

        txtmsv.setAutoscrolls(false);
        txtmsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmsvActionPerformed(evt);
            }
        });
        yah.add(txtmsv, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 138, -1));

        txtho.setAutoscrolls(false);
        yah.add(txtho, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 140, -1));
        yah.add(txtten, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 140, -1));
        yah.add(txtnoisinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 140, -1));
        yah.add(txtghichu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 140, -1));
        yah.add(txtmalop, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 128, -1));
        yah.add(txtgioitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 128, -1));
        yah.add(txtngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 128, -1));
        yah.add(txtdiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 128, -1));
        yah.add(txtnghihoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 126, -1));

        eo.setBackground(new java.awt.Color(255, 255, 255));
        eo.setForeground(new java.awt.Color(0, 0, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên môn", "Học kỳ", "Lần", "Điểm"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(204, 255, 204));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        eo.setViewportView(jTable1);

        yah.add(eo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 522, 210));

        edtenmon.setText("Tên môn");
        yah.add(edtenmon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        edhocky.setText("Học kỳ");
        yah.add(edhocky, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        edlan.setText("Lần");
        yah.add(edlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        lbdiem.setText("Điểm");
        yah.add(lbdiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));
        yah.add(eddiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 40, -1));

        btncapnhat.setText("Cập nhật");
        btncapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatActionPerformed(evt);
            }
        });
        yah.add(btncapnhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(yah, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(yah, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        masv=txtTim.getText();
        switch(combo.getSelectedIndex())
        {
            case 0:
                xemThongTin(txtTim.getText());
                break;
            case 1:
                xemDiem(txtTim.getText());
                break;
            case 2:
                xemDiem(txtTim.getText());
                break;
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void clickTim(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickTim
        // TODO add your handling code here:
        txtTim.setText("");
        lbloi.setText("");
    }//GEN-LAST:event_clickTim

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
        txtTim.setText("Nhập mã sinh viên...");
        anTable();
        anThongTin();
        anCapNhat();
        masv="";
        lbloi.setText("");
        DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
                while(model.getRowCount()!=0)
                    model.removeRow(0);
        switch(combo.getSelectedIndex())
        {
            case 0:
                hienThongTin();
                break;
            case 1:
                eo.setVisible(true);
                break;
            case 2:
                hienCapNhat();
                break;
        }
    }//GEN-LAST:event_comboActionPerformed

    private void txtmsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmsvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmsvActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        eddiem.setText(""+model.getValueAt(jTable1.getSelectedRow(), 3));
        edlan.setText("Lần: "+model.getValueAt(jTable1.getSelectedRow(), 2));
        lan=model.getValueAt(jTable1.getSelectedRow(), 2)+"";
        edhocky.setText("Học kỳ: "+model.getValueAt(jTable1.getSelectedRow(), 1));
        hocky=model.getValueAt(jTable1.getSelectedRow(), 1)+"";
        edtenmon.setText("Môn: "+model.getValueAt(jTable1.getSelectedRow(), 0));
        mamh=model.getValueAt(jTable1.getSelectedRow(), 0)+"";
    }//GEN-LAST:event_jTable1MouseClicked

    private void btncapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhatActionPerformed
        // TODO add your handling code here:
        lbloi.setText("");
        capnhatDiem(masv);
    }//GEN-LAST:event_btncapnhatActionPerformed

    private void txtTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btncapnhat;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextField eddiem;
    private javax.swing.JLabel edhocky;
    private javax.swing.JLabel edlan;
    private javax.swing.JLabel edtenmon;
    private javax.swing.JScrollPane eo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbdiachi;
    private javax.swing.JLabel lbdiem;
    private javax.swing.JLabel lbghichu;
    private javax.swing.JLabel lbgioitinh;
    private javax.swing.JLabel lbho;
    private javax.swing.JLabel lbloi;
    private javax.swing.JLabel lbmalop;
    private javax.swing.JLabel lbmsv;
    private javax.swing.JLabel lbngaysinh;
    private javax.swing.JLabel lbnghihoc;
    private javax.swing.JLabel lbnoisinh;
    private javax.swing.JLabel lbstt;
    private javax.swing.JLabel lbten;
    private javax.swing.JLabel lbthongtin;
    private javax.swing.JTextField txtTim;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtghichu;
    private javax.swing.JTextField txtgioitinh;
    private javax.swing.JTextField txtho;
    private javax.swing.JTextField txtmalop;
    private javax.swing.JTextField txtmsv;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtnghihoc;
    private javax.swing.JTextField txtnoisinh;
    private javax.swing.JTextField txtten;
    private javax.swing.JPanel yah;
    // End of variables declaration//GEN-END:variables

    private void xemThongTin(String masv) {
        try {
            LocateRegistry.getRegistry();
            lbstt.setText("Get registry...");
            ClientServer cs=(ClientServer)Naming.lookup(url);
            lbstt.setText("Naming lookup "+url);
            ThongTin sv =cs.xemThongTin(masv);
            if(sv==null)
            {
                lbloi.setText("Không tìm thấy sinh viên!");
                anThongTin();
            }
            else
            {
                hienThongTin();
                lbloi.setText("");
                lbthongtin.setText("THÔNG TIN SINH VIÊN");
                txtdiachi.setText(sv.getDiachi());
                txtghichu.setText(sv.getGhichu());
                if(sv.getPhai().equals("1"))
                    txtgioitinh.setText("Nam");
                else
                    txtgioitinh.setText("Nu");
                txtmalop.setText(sv.getMalop());
                txtmsv.setText(sv.getMasv());
                txtngaysinh.setText(sv.getNgaysinh());
                if(sv.getNghihoc().equals("1"))
                    txtnghihoc.setText("Nghỉ");
                else
                    txtnghihoc.setText("Không");
                txtnoisinh.setText(sv.getNoisinh());
                txtten.setText(sv.getTen());
                txtho.setText(sv.getHo());
            }
                
        } catch (RemoteException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void anThongTin(){
        txtnghihoc.setVisible(false);
        txtdiachi.setVisible(false);
        txtghichu.setVisible(false);
        txtho.setVisible(false);
        txtgioitinh.setVisible(false);
        txtmalop.setVisible(false);
        txtmsv.setVisible(false);
        txtngaysinh.setVisible(false);
        txtnoisinh.setVisible(false);
        txtten.setVisible(false);
        lbdiachi.setText("");
        lbghichu.setText("");
        lbgioitinh.setText("");
        lbmalop.setText("");
        lbmsv.setText("");
        lbngaysinh.setText("");
        lbnghihoc.setText("");
        lbnoisinh.setText("");
        lbten.setText("");
        lbho.setText("");
        lbthongtin.setText("");
    }
    public void hienThongTin(){
        txtnghihoc.setVisible(true);
        txtdiachi.setVisible(true);
        txtghichu.setVisible(true);
        txtho.setVisible(true);
        txtgioitinh.setVisible(true);
        txtmalop.setVisible(true);
        txtmsv.setVisible(true);
        txtngaysinh.setVisible(true);
        txtnoisinh.setVisible(true);
        txtten.setVisible(true);
        lbdiachi.setText("Địa chỉ:");
        lbghichu.setText("Ghi chú:");
        lbgioitinh.setText("Giới tính:");
        lbmalop.setText("Lớp:");
        lbmsv.setText("Mã sinh viên:");
        lbngaysinh.setText("Ngày sinh:");
        lbnghihoc.setText("Nghỉ học:");
        lbnoisinh.setText("Nơi sinh:");
        lbten.setText("Tên:");
        lbho.setText("Họ:");
        lbthongtin.setText("THÔNG TIN SINH VIÊN");
    }

    private void xemDiem(String masv) {
        try {
            LocateRegistry.getRegistry();
            ClientServer cs =(ClientServer)Naming.lookup(url);
            ArrayList<Diem> arr =cs.xemDiem(masv);
            if(arr.isEmpty())
            {
                lbloi.setText("Không tìm thấy!");
            }
            else{
                lbloi.setText("");
                eo.setVisible(true);
                lbthongtin.setText("ĐIỂM CỦA SINH VIÊN "+masv);
                DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
                while(model.getRowCount()!=0)
                    model.removeRow(0);
                for(Diem i:arr){
                    model.addRow(new Object[]{i.getTenmh(),i.getHocky(),i.getLan(),i.getDiem()});
                }
                
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void anTable() {
        eo.setVisible(false);
    }

    private void capnhatDiem(String a) {
        try {
            LocateRegistry.getRegistry();
            ClientServer cs=(ClientServer)Naming.lookup(url);
            lbthongtin.setText(cs.updateDiem(a, mamh, hocky, lan, eddiem.getText()));
            xemDiem(a);
            lbthongtin.setText(cs.updateDiem(a, mamh, hocky, lan, eddiem.getText()));
        } catch (RemoteException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void anCapNhat() {
        eddiem.setText("");
        lbdiem.setText("");
        edhocky.setText("");
        edlan.setText("");
        edtenmon.setText("");
        eddiem.setVisible(false);
        btncapnhat.setVisible(false);
    }
    private void hienCapNhat(){
        lbdiem.setText("Điểm");
        edhocky.setText("Học kỳ:");
        edlan.setText("Lần");
        edtenmon.setText("Môn học:");
        eo.setVisible(true);
        eddiem.setVisible(true);
        btncapnhat.setVisible(true);
    }

}
